name: flutter_appnovo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0
  material_color_utilities: ^0.11.1
  flutter_masked_text2: ^0.9.1
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.1
  provider: ^6.0.5
  http: ^0.13.6
  supabase_flutter: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - lib/assets/pizza_logo.png
    - lib/assets/pizza_logo2.png
    - lib/assets/location_icon.png
    - lib/assets/google_icon.png
    - lib/assets/pizzas/a_moda.png
    - lib/assets/pizzas/bolodemorango.png
    - lib/assets/pizzas/calabresa.png
    - lib/assets/pizzas/chocolatemorango.png
    - lib/assets/pizzas/docedeleite.png
    - lib/assets/pizzas/filemignon.png
    - lib/assets/pizzas/heinekenlongneck.png
    - lib/assets/pizzas/marguerita.png
    - lib/assets/pizzas/minicalabresa.png
    - lib/assets/pizzas/minifrangocatupiry.png
    - lib/assets/pizzas/miniqueijo.png
    - lib/assets/pizzas/mozarelabuffala.png
    - lib/assets/pizzas/pepperoni.png
    - lib/assets/pizzas/quatroqueijos.png
    - lib/assets/pizzas/queijobacon.png
    - lib/assets/pizzas/romeujulieta.png
    - lib/assets/pizzas/sucodelaranja.png
    - lib/assets/pizzas/vegetariana.png